---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: kafkatopics.kafka.banzaicloud.io
spec:
  group: kafka.banzaicloud.io
  names:
    kind: KafkaTopic
    listKind: KafkaTopicList
    plural: kafkatopics
    singular: kafkatopic
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KafkaTopic is the Schema for the kafkatopics API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KafkaTopicSpec defines the desired state of KafkaTopic
            properties:
              clusterRef:
                description: ClusterReference states a reference to a cluster for
                  topic/user provisioning
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                type: object
              config:
                additionalProperties:
                  type: string
                type: object
              name:
                type: string
              partitions:
                description: Partitions defines the desired number of partitions;
                  must be positive, or -1 to signify using the broker's default
                format: int32
                minimum: -1
                type: integer
              replicationFactor:
                description: ReplicationFactor defines the desired replication factor;
                  must be positive, or -1 to signify using the broker's default
                format: int32
                minimum: -1
                type: integer
            required:
            - clusterRef
            - name
            - partitions
            - replicationFactor
            type: object
          status:
            description: KafkaTopicStatus defines the observed state of KafkaTopic
            properties:
              managedBy:
                description: 'ManagedBy describes who is the manager of the Kafka
                  topic. When its value is not "koperator" then modifications to the
                  topic configurations of the KafkaTopic CR will not be propagated
                  to the Kafka topic. Manager of the Kafka topic can be changed by
                  adding the "managedBy: <manager>" annotation to the KafkaTopic CR.'
                type: string
              state:
                description: TopicState defines the state of a KafkaTopic
                type: string
            required:
            - managedBy
            - state
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
