approved = [
  "mit",
  "apache-2.0",
  "bsd-3-clause",
  "bsd-2-clause",
  "mpl-2.0",
]

ignored = [
  "github.com/ghodss/yaml",
  "github.com/gogo/protobuf",
  "github.com/hpcloud/tail",
  "github.com/inconshreveable/mousetrap",
  "sigs.k8s.io/yaml",
  "github.com/rcrowley/go-metrics",
  "go.uber.org/atomic",
  "go.uber.org/multierr",
  "emperror.dev/errors",
  "emperror.dev/emperror",
  "go.uber.org/zap",
  "google.golang.org/grpc",
  "google.golang.org/genproto",
  "gomodules.xyz/jsonpatch/v2",
  "gopkg.in/fsnotify.v1",
  "k8s.io/apiextensions-apiserver",
  "github.com/imdario/mergo",
  "github.com/spf13/pflag",
  "cloud.google.com/go",
  "github.com/matttproud/golang_protobuf_extensions",
  "github.com/prometheus/procfs",
  "github.com/google/uuid",
  "github.com/pborman/uuid",
  "github.com/prometheus/client_model",
  "github.com/prometheus/",
  "github.com/prometheus/client_golang",

  "github.com/davecgh/go-spew", # ISC license
]
