apiVersion: v1
name: kafka-operator
version: 0.22.0-dev.1
description: kafka-operator manages Kafka deployments on Kubernetes
sources:
  - https://github.com/banzaicloud/koperator
appVersion: v0.22.0-dev.1
