apiVersion: v1
name: kafka-operator
version: 0.4.5
description: kafka-operator manages Kafka deployments on Kubernetes
sources:
  - https://github.com/banzaicloud/kafka-operator
appVersion: v0.15.0-dev.1
