apiVersion: banzaicloud.banzaicloud.io/v1alpha1
kind: KafkaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: kafka
spec:
  # Add fields here
  brokers: 3
  annotations: {}
  image: "wurstmeister/kafka:2.12-2.1.0"
  zkAddress: "example-zookeepercluster-client.zookeeper:2181"
  restProxyEnabled: true
  brokerConfig: |
    num.network.threads=2
    log.dirs=/kafka-logs/kafka
    default.replication.factor=3
    num.partitions=3
  listeners:
    externalListener:
      - type: "ssl"
        name: "external"
        externalStartingPort: 19090
        containerPort: 9094
    internalListener:
      - type: "ssl"
        name: "ssl"
        containerPort: 29092
        usedForInnerBrokerCommunication: true
    tlsSecretName: "my-tls-cert-kafka1"
  serviceAccount: ""
  storageSize: "10Gi"
