---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: cruisecontroloperations.kafka.banzaicloud.io
spec:
  group: kafka.banzaicloud.io
  names:
    kind: CruiseControlOperation
    listKind: CruiseControlOperationList
    plural: cruisecontroloperations
    singular: cruisecontroloperation
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CruiseControlOperation is the Schema for the cruiseControlOperation
          API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CruiseControlOperationSpec defines the desired state of CruiseControlOperation.
            properties:
              errorPolicy:
                default: retry
                description: ErrorPolicy defines how failed Cruise Control operation
                  should be handled. When it is "retry", the Koperator re-executes
                  the failed task in every 30 sec (by default). When it is "ignore",
                  the Koperator handles the failed task as completed.
                enum:
                - ignore
                - retry
                type: string
              ttlSecondsAfterFinished:
                description: 'When TTLSecondsAfterFinished is specified, the created
                  and finished (completed successfully or completedWithError and errorPolicy:
                  ignore) cruiseControlOperation custom resource will be deleted after
                  the given time elapsed. When it is 0 then the resource is going
                  to be deleted instantly after the operation is finished. When it
                  is not specified the resource is not going to be removed. Value
                  can be only zero and positive integers'
                minimum: 0
                type: integer
            type: object
          status:
            description: CruiseControlOperationStatus defines the observed state of
              CruiseControlOperation.
            properties:
              currentTask:
                description: CruiseControlTask defines the observed state of the Cruise
                  Control user task.
                properties:
                  errorMessage:
                    type: string
                  finished:
                    format: date-time
                    type: string
                  httpRequest:
                    description: HTTPRequest is a Cruise Control user task HTTP request.
                    type: string
                  httpResponseCode:
                    type: integer
                  id:
                    type: string
                  operation:
                    description: Operation defines the Cruise Control operation kind.
                    type: string
                  parameters:
                    additionalProperties:
                      type: string
                    description: Parameters defines the configuration of the operation.
                    type: object
                  started:
                    format: date-time
                    type: string
                  state:
                    description: State is the current state of the Cruise Control
                      user task.
                    type: string
                  summary:
                    additionalProperties:
                      type: string
                    description: Summary of the Cruise Control user task execution
                      proposal.
                    type: object
                required:
                - operation
                type: object
              errorPolicy:
                description: ErrorPolicyType defines methods of handling Cruise Control
                  user task errors.
                type: string
              failedTasks:
                items:
                  description: CruiseControlTask defines the observed state of the
                    Cruise Control user task.
                  properties:
                    errorMessage:
                      type: string
                    finished:
                      format: date-time
                      type: string
                    httpRequest:
                      description: HTTPRequest is a Cruise Control user task HTTP
                        request.
                      type: string
                    httpResponseCode:
                      type: integer
                    id:
                      type: string
                    operation:
                      description: Operation defines the Cruise Control operation
                        kind.
                      type: string
                    parameters:
                      additionalProperties:
                        type: string
                      description: Parameters defines the configuration of the operation.
                      type: object
                    started:
                      format: date-time
                      type: string
                    state:
                      description: State is the current state of the Cruise Control
                        user task.
                      type: string
                    summary:
                      additionalProperties:
                        type: string
                      description: Summary of the Cruise Control user task execution
                        proposal.
                      type: object
                  required:
                  - operation
                  type: object
                type: array
              retryCount:
                type: integer
            required:
            - errorPolicy
            - retryCount
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
