name: Docker / Performance test load
on:
  push:
    branches:
      - master
    tags:
      - "koperator-performance-test-load/v?[0-9]+.[0-9]+.[0-9]+"
env:
  PLATFORMS: linux/amd64
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Determine tag or commit
        uses: haya14busa/action-cond@v1
        id: refortag
        with:
          cond: ${{ startsWith(github.ref, 'refs/tags/') }}
          if_true: ${{ github.ref }}
          if_false: latest

      - name: Determine image tag
        id: imagetag
        run: echo "value=${TAG_OR_BRANCH##*/}" >> $GITHUB_OUTPUT
        env:
          TAG_OR_BRANCH: ${{ steps.refortag.outputs.value }}

      - name: Setup Docker metadata
        id: setup-docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/banzaicloud/koperator-performance-test-load

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build koperator-performance-test-load
        uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/banzaicloud/koperator-performance-test-load:${{ steps.imagetag.outputs.value }}
          file: docs/benchmarks/loadgens/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
